<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Window_FileNameSetter</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Page Update="Languages\Lang.de.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
    <Page Update="Languages\Lang.en.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
    <Page Update="Languages\Lang.es.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
    <Page Update="Languages\Lang.fr.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
    <Page Update="Languages\Lang.ja.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
    <Page Update="Languages\Lang.ko.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
    <Page Update="Languages\Lang.ru.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
    <Page Update="Languages\Lang.zh.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
